// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: server/server.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	GetSocialFinancingStock(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SocialFinancingStockResponse, error)
	// 期货 伦铜:CAD
	GetFuturesForeignHist(ctx context.Context, in *FturesFoewignRequest, opts ...grpc.CallOption) (*FturesFoewignResponse, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) GetSocialFinancingStock(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SocialFinancingStockResponse, error) {
	out := new(SocialFinancingStockResponse)
	err := c.cc.Invoke(ctx, "/server.Greeter/GetSocialFinancingStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetFuturesForeignHist(ctx context.Context, in *FturesFoewignRequest, opts ...grpc.CallOption) (*FturesFoewignResponse, error) {
	out := new(FturesFoewignResponse)
	err := c.cc.Invoke(ctx, "/server.Greeter/GetFuturesForeignHist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations should embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	// Sends a greeting
	GetSocialFinancingStock(context.Context, *emptypb.Empty) (*SocialFinancingStockResponse, error)
	// 期货 伦铜:CAD
	GetFuturesForeignHist(context.Context, *FturesFoewignRequest) (*FturesFoewignResponse, error)
}

// UnimplementedGreeterServer should be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) GetSocialFinancingStock(context.Context, *emptypb.Empty) (*SocialFinancingStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSocialFinancingStock not implemented")
}
func (UnimplementedGreeterServer) GetFuturesForeignHist(context.Context, *FturesFoewignRequest) (*FturesFoewignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFuturesForeignHist not implemented")
}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_GetSocialFinancingStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetSocialFinancingStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Greeter/GetSocialFinancingStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetSocialFinancingStock(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetFuturesForeignHist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FturesFoewignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetFuturesForeignHist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Greeter/GetFuturesForeignHist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetFuturesForeignHist(ctx, req.(*FturesFoewignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSocialFinancingStock",
			Handler:    _Greeter_GetSocialFinancingStock_Handler,
		},
		{
			MethodName: "GetFuturesForeignHist",
			Handler:    _Greeter_GetFuturesForeignHist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/server.proto",
}
