// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                 = new(Query)
	BondZhUsRateModel *bondZhUsRateModel
	PePbPsDvTotalmv   *pePbPsDvTotalmv
	SH300PEModel      *sH300PEModel
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	BondZhUsRateModel = &Q.BondZhUsRateModel
	PePbPsDvTotalmv = &Q.PePbPsDvTotalmv
	SH300PEModel = &Q.SH300PEModel
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		BondZhUsRateModel: newBondZhUsRateModel(db, opts...),
		PePbPsDvTotalmv:   newPePbPsDvTotalmv(db, opts...),
		SH300PEModel:      newSH300PEModel(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	BondZhUsRateModel bondZhUsRateModel
	PePbPsDvTotalmv   pePbPsDvTotalmv
	SH300PEModel      sH300PEModel
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		BondZhUsRateModel: q.BondZhUsRateModel.clone(db),
		PePbPsDvTotalmv:   q.PePbPsDvTotalmv.clone(db),
		SH300PEModel:      q.SH300PEModel.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		BondZhUsRateModel: q.BondZhUsRateModel.replaceDB(db),
		PePbPsDvTotalmv:   q.PePbPsDvTotalmv.replaceDB(db),
		SH300PEModel:      q.SH300PEModel.replaceDB(db),
	}
}

type queryCtx struct {
	BondZhUsRateModel *bondZhUsRateModelDo
	PePbPsDvTotalmv   *pePbPsDvTotalmvDo
	SH300PEModel      *sH300PEModelDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		BondZhUsRateModel: q.BondZhUsRateModel.WithContext(ctx),
		PePbPsDvTotalmv:   q.PePbPsDvTotalmv.WithContext(ctx),
		SH300PEModel:      q.SH300PEModel.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	return &QueryTx{q.clone(q.db.Begin(opts...))}
}

type QueryTx struct{ *Query }

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
