// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/chenhaonan-eth/dao/dal/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMacroPMIModel(db *gorm.DB, opts ...gen.DOOption) macroPMIModel {
	_macroPMIModel := macroPMIModel{}

	_macroPMIModel.macroPMIModelDo.UseDB(db, opts...)
	_macroPMIModel.macroPMIModelDo.UseModel(&model.MacroPMIModel{})

	tableName := _macroPMIModel.macroPMIModelDo.TableName()
	_macroPMIModel.ALL = field.NewAsterisk(tableName)
	_macroPMIModel.Date = field.NewString(tableName, "date")
	_macroPMIModel.Country = field.NewString(tableName, "country")
	_macroPMIModel.Pmi = field.NewString(tableName, "pmi")

	_macroPMIModel.fillFieldMap()

	return _macroPMIModel
}

type macroPMIModel struct {
	macroPMIModelDo macroPMIModelDo

	ALL     field.Asterisk
	Date    field.String
	Country field.String
	Pmi     field.String

	fieldMap map[string]field.Expr
}

func (m macroPMIModel) Table(newTableName string) *macroPMIModel {
	m.macroPMIModelDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m macroPMIModel) As(alias string) *macroPMIModel {
	m.macroPMIModelDo.DO = *(m.macroPMIModelDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *macroPMIModel) updateTableName(table string) *macroPMIModel {
	m.ALL = field.NewAsterisk(table)
	m.Date = field.NewString(table, "date")
	m.Country = field.NewString(table, "country")
	m.Pmi = field.NewString(table, "pmi")

	m.fillFieldMap()

	return m
}

func (m *macroPMIModel) WithContext(ctx context.Context) *macroPMIModelDo {
	return m.macroPMIModelDo.WithContext(ctx)
}

func (m macroPMIModel) TableName() string { return m.macroPMIModelDo.TableName() }

func (m macroPMIModel) Alias() string { return m.macroPMIModelDo.Alias() }

func (m *macroPMIModel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *macroPMIModel) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 3)
	m.fieldMap["date"] = m.Date
	m.fieldMap["country"] = m.Country
	m.fieldMap["pmi"] = m.Pmi
}

func (m macroPMIModel) clone(db *gorm.DB) macroPMIModel {
	m.macroPMIModelDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m macroPMIModel) replaceDB(db *gorm.DB) macroPMIModel {
	m.macroPMIModelDo.ReplaceDB(db)
	return m
}

type macroPMIModelDo struct{ gen.DO }

func (m macroPMIModelDo) Debug() *macroPMIModelDo {
	return m.withDO(m.DO.Debug())
}

func (m macroPMIModelDo) WithContext(ctx context.Context) *macroPMIModelDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m macroPMIModelDo) ReadDB() *macroPMIModelDo {
	return m.Clauses(dbresolver.Read)
}

func (m macroPMIModelDo) WriteDB() *macroPMIModelDo {
	return m.Clauses(dbresolver.Write)
}

func (m macroPMIModelDo) Session(config *gorm.Session) *macroPMIModelDo {
	return m.withDO(m.DO.Session(config))
}

func (m macroPMIModelDo) Clauses(conds ...clause.Expression) *macroPMIModelDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m macroPMIModelDo) Returning(value interface{}, columns ...string) *macroPMIModelDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m macroPMIModelDo) Not(conds ...gen.Condition) *macroPMIModelDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m macroPMIModelDo) Or(conds ...gen.Condition) *macroPMIModelDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m macroPMIModelDo) Select(conds ...field.Expr) *macroPMIModelDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m macroPMIModelDo) Where(conds ...gen.Condition) *macroPMIModelDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m macroPMIModelDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *macroPMIModelDo {
	return m.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (m macroPMIModelDo) Order(conds ...field.Expr) *macroPMIModelDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m macroPMIModelDo) Distinct(cols ...field.Expr) *macroPMIModelDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m macroPMIModelDo) Omit(cols ...field.Expr) *macroPMIModelDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m macroPMIModelDo) Join(table schema.Tabler, on ...field.Expr) *macroPMIModelDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m macroPMIModelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *macroPMIModelDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m macroPMIModelDo) RightJoin(table schema.Tabler, on ...field.Expr) *macroPMIModelDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m macroPMIModelDo) Group(cols ...field.Expr) *macroPMIModelDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m macroPMIModelDo) Having(conds ...gen.Condition) *macroPMIModelDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m macroPMIModelDo) Limit(limit int) *macroPMIModelDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m macroPMIModelDo) Offset(offset int) *macroPMIModelDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m macroPMIModelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *macroPMIModelDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m macroPMIModelDo) Unscoped() *macroPMIModelDo {
	return m.withDO(m.DO.Unscoped())
}

func (m macroPMIModelDo) Create(values ...*model.MacroPMIModel) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m macroPMIModelDo) CreateInBatches(values []*model.MacroPMIModel, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m macroPMIModelDo) Save(values ...*model.MacroPMIModel) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m macroPMIModelDo) First() (*model.MacroPMIModel, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MacroPMIModel), nil
	}
}

func (m macroPMIModelDo) Take() (*model.MacroPMIModel, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MacroPMIModel), nil
	}
}

func (m macroPMIModelDo) Last() (*model.MacroPMIModel, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MacroPMIModel), nil
	}
}

func (m macroPMIModelDo) Find() ([]*model.MacroPMIModel, error) {
	result, err := m.DO.Find()
	return result.([]*model.MacroPMIModel), err
}

func (m macroPMIModelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MacroPMIModel, err error) {
	buf := make([]*model.MacroPMIModel, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m macroPMIModelDo) FindInBatches(result *[]*model.MacroPMIModel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m macroPMIModelDo) Attrs(attrs ...field.AssignExpr) *macroPMIModelDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m macroPMIModelDo) Assign(attrs ...field.AssignExpr) *macroPMIModelDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m macroPMIModelDo) Joins(fields ...field.RelationField) *macroPMIModelDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m macroPMIModelDo) Preload(fields ...field.RelationField) *macroPMIModelDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m macroPMIModelDo) FirstOrInit() (*model.MacroPMIModel, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MacroPMIModel), nil
	}
}

func (m macroPMIModelDo) FirstOrCreate() (*model.MacroPMIModel, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MacroPMIModel), nil
	}
}

func (m macroPMIModelDo) FindByPage(offset int, limit int) (result []*model.MacroPMIModel, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m macroPMIModelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m macroPMIModelDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m macroPMIModelDo) Delete(models ...*model.MacroPMIModel) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *macroPMIModelDo) withDO(do gen.Dao) *macroPMIModelDo {
	m.DO = *do.(*gen.DO)
	return m
}
