// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/chenhaonan-eth/dao/dal/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMacroChinaMoneySupply(db *gorm.DB, opts ...gen.DOOption) macroChinaMoneySupply {
	_macroChinaMoneySupply := macroChinaMoneySupply{}

	_macroChinaMoneySupply.macroChinaMoneySupplyDo.UseDB(db, opts...)
	_macroChinaMoneySupply.macroChinaMoneySupplyDo.UseModel(&model.MacroChinaMoneySupply{})

	tableName := _macroChinaMoneySupply.macroChinaMoneySupplyDo.TableName()
	_macroChinaMoneySupply.ALL = field.NewAsterisk(tableName)
	_macroChinaMoneySupply.Date = field.NewString(tableName, "date")
	_macroChinaMoneySupply.M2 = field.NewFloat64(tableName, "m2")
	_macroChinaMoneySupply.M2YearOnYear = field.NewFloat64(tableName, "m2_year_on_year")
	_macroChinaMoneySupply.M2YearOverYear = field.NewFloat64(tableName, "m2_year_over_year")
	_macroChinaMoneySupply.M1 = field.NewFloat64(tableName, "m1")
	_macroChinaMoneySupply.M1YearOnYear = field.NewFloat64(tableName, "m1_year_on_year")
	_macroChinaMoneySupply.M1YearOverYear = field.NewFloat64(tableName, "m1_year_over_year")
	_macroChinaMoneySupply.M0 = field.NewFloat64(tableName, "m0")
	_macroChinaMoneySupply.M0YearOnYear = field.NewFloat64(tableName, "m0_year_on_year")
	_macroChinaMoneySupply.M0YearOverYear = field.NewFloat64(tableName, "m0_year_over_year")

	_macroChinaMoneySupply.fillFieldMap()

	return _macroChinaMoneySupply
}

type macroChinaMoneySupply struct {
	macroChinaMoneySupplyDo macroChinaMoneySupplyDo

	ALL            field.Asterisk
	Date           field.String
	M2             field.Float64
	M2YearOnYear   field.Float64
	M2YearOverYear field.Float64
	M1             field.Float64
	M1YearOnYear   field.Float64
	M1YearOverYear field.Float64
	M0             field.Float64
	M0YearOnYear   field.Float64
	M0YearOverYear field.Float64

	fieldMap map[string]field.Expr
}

func (m macroChinaMoneySupply) Table(newTableName string) *macroChinaMoneySupply {
	m.macroChinaMoneySupplyDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m macroChinaMoneySupply) As(alias string) *macroChinaMoneySupply {
	m.macroChinaMoneySupplyDo.DO = *(m.macroChinaMoneySupplyDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *macroChinaMoneySupply) updateTableName(table string) *macroChinaMoneySupply {
	m.ALL = field.NewAsterisk(table)
	m.Date = field.NewString(table, "date")
	m.M2 = field.NewFloat64(table, "m2")
	m.M2YearOnYear = field.NewFloat64(table, "m2_year_on_year")
	m.M2YearOverYear = field.NewFloat64(table, "m2_year_over_year")
	m.M1 = field.NewFloat64(table, "m1")
	m.M1YearOnYear = field.NewFloat64(table, "m1_year_on_year")
	m.M1YearOverYear = field.NewFloat64(table, "m1_year_over_year")
	m.M0 = field.NewFloat64(table, "m0")
	m.M0YearOnYear = field.NewFloat64(table, "m0_year_on_year")
	m.M0YearOverYear = field.NewFloat64(table, "m0_year_over_year")

	m.fillFieldMap()

	return m
}

func (m *macroChinaMoneySupply) WithContext(ctx context.Context) *macroChinaMoneySupplyDo {
	return m.macroChinaMoneySupplyDo.WithContext(ctx)
}

func (m macroChinaMoneySupply) TableName() string { return m.macroChinaMoneySupplyDo.TableName() }

func (m macroChinaMoneySupply) Alias() string { return m.macroChinaMoneySupplyDo.Alias() }

func (m *macroChinaMoneySupply) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *macroChinaMoneySupply) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 10)
	m.fieldMap["date"] = m.Date
	m.fieldMap["m2"] = m.M2
	m.fieldMap["m2_year_on_year"] = m.M2YearOnYear
	m.fieldMap["m2_year_over_year"] = m.M2YearOverYear
	m.fieldMap["m1"] = m.M1
	m.fieldMap["m1_year_on_year"] = m.M1YearOnYear
	m.fieldMap["m1_year_over_year"] = m.M1YearOverYear
	m.fieldMap["m0"] = m.M0
	m.fieldMap["m0_year_on_year"] = m.M0YearOnYear
	m.fieldMap["m0_year_over_year"] = m.M0YearOverYear
}

func (m macroChinaMoneySupply) clone(db *gorm.DB) macroChinaMoneySupply {
	m.macroChinaMoneySupplyDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m macroChinaMoneySupply) replaceDB(db *gorm.DB) macroChinaMoneySupply {
	m.macroChinaMoneySupplyDo.ReplaceDB(db)
	return m
}

type macroChinaMoneySupplyDo struct{ gen.DO }

func (m macroChinaMoneySupplyDo) Debug() *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Debug())
}

func (m macroChinaMoneySupplyDo) WithContext(ctx context.Context) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m macroChinaMoneySupplyDo) ReadDB() *macroChinaMoneySupplyDo {
	return m.Clauses(dbresolver.Read)
}

func (m macroChinaMoneySupplyDo) WriteDB() *macroChinaMoneySupplyDo {
	return m.Clauses(dbresolver.Write)
}

func (m macroChinaMoneySupplyDo) Session(config *gorm.Session) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Session(config))
}

func (m macroChinaMoneySupplyDo) Clauses(conds ...clause.Expression) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m macroChinaMoneySupplyDo) Returning(value interface{}, columns ...string) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m macroChinaMoneySupplyDo) Not(conds ...gen.Condition) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m macroChinaMoneySupplyDo) Or(conds ...gen.Condition) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m macroChinaMoneySupplyDo) Select(conds ...field.Expr) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m macroChinaMoneySupplyDo) Where(conds ...gen.Condition) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m macroChinaMoneySupplyDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *macroChinaMoneySupplyDo {
	return m.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (m macroChinaMoneySupplyDo) Order(conds ...field.Expr) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m macroChinaMoneySupplyDo) Distinct(cols ...field.Expr) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m macroChinaMoneySupplyDo) Omit(cols ...field.Expr) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m macroChinaMoneySupplyDo) Join(table schema.Tabler, on ...field.Expr) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m macroChinaMoneySupplyDo) LeftJoin(table schema.Tabler, on ...field.Expr) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m macroChinaMoneySupplyDo) RightJoin(table schema.Tabler, on ...field.Expr) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m macroChinaMoneySupplyDo) Group(cols ...field.Expr) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m macroChinaMoneySupplyDo) Having(conds ...gen.Condition) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m macroChinaMoneySupplyDo) Limit(limit int) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m macroChinaMoneySupplyDo) Offset(offset int) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m macroChinaMoneySupplyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m macroChinaMoneySupplyDo) Unscoped() *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Unscoped())
}

func (m macroChinaMoneySupplyDo) Create(values ...*model.MacroChinaMoneySupply) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m macroChinaMoneySupplyDo) CreateInBatches(values []*model.MacroChinaMoneySupply, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m macroChinaMoneySupplyDo) Save(values ...*model.MacroChinaMoneySupply) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m macroChinaMoneySupplyDo) First() (*model.MacroChinaMoneySupply, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MacroChinaMoneySupply), nil
	}
}

func (m macroChinaMoneySupplyDo) Take() (*model.MacroChinaMoneySupply, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MacroChinaMoneySupply), nil
	}
}

func (m macroChinaMoneySupplyDo) Last() (*model.MacroChinaMoneySupply, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MacroChinaMoneySupply), nil
	}
}

func (m macroChinaMoneySupplyDo) Find() ([]*model.MacroChinaMoneySupply, error) {
	result, err := m.DO.Find()
	return result.([]*model.MacroChinaMoneySupply), err
}

func (m macroChinaMoneySupplyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MacroChinaMoneySupply, err error) {
	buf := make([]*model.MacroChinaMoneySupply, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m macroChinaMoneySupplyDo) FindInBatches(result *[]*model.MacroChinaMoneySupply, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m macroChinaMoneySupplyDo) Attrs(attrs ...field.AssignExpr) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m macroChinaMoneySupplyDo) Assign(attrs ...field.AssignExpr) *macroChinaMoneySupplyDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m macroChinaMoneySupplyDo) Joins(fields ...field.RelationField) *macroChinaMoneySupplyDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m macroChinaMoneySupplyDo) Preload(fields ...field.RelationField) *macroChinaMoneySupplyDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m macroChinaMoneySupplyDo) FirstOrInit() (*model.MacroChinaMoneySupply, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MacroChinaMoneySupply), nil
	}
}

func (m macroChinaMoneySupplyDo) FirstOrCreate() (*model.MacroChinaMoneySupply, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MacroChinaMoneySupply), nil
	}
}

func (m macroChinaMoneySupplyDo) FindByPage(offset int, limit int) (result []*model.MacroChinaMoneySupply, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m macroChinaMoneySupplyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m macroChinaMoneySupplyDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m macroChinaMoneySupplyDo) Delete(models ...*model.MacroChinaMoneySupply) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *macroChinaMoneySupplyDo) withDO(do gen.Dao) *macroChinaMoneySupplyDo {
	m.DO = *do.(*gen.DO)
	return m
}
