// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/chenhaonan-eth/dao/dal/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newMacroChinaConsumerGoodsRetail(db *gorm.DB, opts ...gen.DOOption) macroChinaConsumerGoodsRetail {
	_macroChinaConsumerGoodsRetail := macroChinaConsumerGoodsRetail{}

	_macroChinaConsumerGoodsRetail.macroChinaConsumerGoodsRetailDo.UseDB(db, opts...)
	_macroChinaConsumerGoodsRetail.macroChinaConsumerGoodsRetailDo.UseModel(&model.MacroChinaConsumerGoodsRetail{})

	tableName := _macroChinaConsumerGoodsRetail.macroChinaConsumerGoodsRetailDo.TableName()
	_macroChinaConsumerGoodsRetail.ALL = field.NewAsterisk(tableName)
	_macroChinaConsumerGoodsRetail.Date = field.NewString(tableName, "date")
	_macroChinaConsumerGoodsRetail.TotalRetailSales = field.NewFloat64(tableName, "total_retail_sales")
	_macroChinaConsumerGoodsRetail.YearOnYear = field.NewFloat64(tableName, "year_on_year")
	_macroChinaConsumerGoodsRetail.YearOverYear = field.NewFloat64(tableName, "year_over_year")
	_macroChinaConsumerGoodsRetail.TotalAccumulation = field.NewFloat64(tableName, "total_accumulation")
	_macroChinaConsumerGoodsRetail.TotalAccumulationYearOnYear = field.NewFloat64(tableName, "total_accumulation_year_on_year")

	_macroChinaConsumerGoodsRetail.fillFieldMap()

	return _macroChinaConsumerGoodsRetail
}

type macroChinaConsumerGoodsRetail struct {
	macroChinaConsumerGoodsRetailDo macroChinaConsumerGoodsRetailDo

	ALL                         field.Asterisk
	Date                        field.String
	TotalRetailSales            field.Float64
	YearOnYear                  field.Float64
	YearOverYear                field.Float64
	TotalAccumulation           field.Float64
	TotalAccumulationYearOnYear field.Float64

	fieldMap map[string]field.Expr
}

func (m macroChinaConsumerGoodsRetail) Table(newTableName string) *macroChinaConsumerGoodsRetail {
	m.macroChinaConsumerGoodsRetailDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m macroChinaConsumerGoodsRetail) As(alias string) *macroChinaConsumerGoodsRetail {
	m.macroChinaConsumerGoodsRetailDo.DO = *(m.macroChinaConsumerGoodsRetailDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *macroChinaConsumerGoodsRetail) updateTableName(table string) *macroChinaConsumerGoodsRetail {
	m.ALL = field.NewAsterisk(table)
	m.Date = field.NewString(table, "date")
	m.TotalRetailSales = field.NewFloat64(table, "total_retail_sales")
	m.YearOnYear = field.NewFloat64(table, "year_on_year")
	m.YearOverYear = field.NewFloat64(table, "year_over_year")
	m.TotalAccumulation = field.NewFloat64(table, "total_accumulation")
	m.TotalAccumulationYearOnYear = field.NewFloat64(table, "total_accumulation_year_on_year")

	m.fillFieldMap()

	return m
}

func (m *macroChinaConsumerGoodsRetail) WithContext(ctx context.Context) *macroChinaConsumerGoodsRetailDo {
	return m.macroChinaConsumerGoodsRetailDo.WithContext(ctx)
}

func (m macroChinaConsumerGoodsRetail) TableName() string {
	return m.macroChinaConsumerGoodsRetailDo.TableName()
}

func (m macroChinaConsumerGoodsRetail) Alias() string {
	return m.macroChinaConsumerGoodsRetailDo.Alias()
}

func (m *macroChinaConsumerGoodsRetail) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *macroChinaConsumerGoodsRetail) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 6)
	m.fieldMap["date"] = m.Date
	m.fieldMap["total_retail_sales"] = m.TotalRetailSales
	m.fieldMap["year_on_year"] = m.YearOnYear
	m.fieldMap["year_over_year"] = m.YearOverYear
	m.fieldMap["total_accumulation"] = m.TotalAccumulation
	m.fieldMap["total_accumulation_year_on_year"] = m.TotalAccumulationYearOnYear
}

func (m macroChinaConsumerGoodsRetail) clone(db *gorm.DB) macroChinaConsumerGoodsRetail {
	m.macroChinaConsumerGoodsRetailDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m macroChinaConsumerGoodsRetail) replaceDB(db *gorm.DB) macroChinaConsumerGoodsRetail {
	m.macroChinaConsumerGoodsRetailDo.ReplaceDB(db)
	return m
}

type macroChinaConsumerGoodsRetailDo struct{ gen.DO }

func (m macroChinaConsumerGoodsRetailDo) Debug() *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Debug())
}

func (m macroChinaConsumerGoodsRetailDo) WithContext(ctx context.Context) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m macroChinaConsumerGoodsRetailDo) ReadDB() *macroChinaConsumerGoodsRetailDo {
	return m.Clauses(dbresolver.Read)
}

func (m macroChinaConsumerGoodsRetailDo) WriteDB() *macroChinaConsumerGoodsRetailDo {
	return m.Clauses(dbresolver.Write)
}

func (m macroChinaConsumerGoodsRetailDo) Session(config *gorm.Session) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Session(config))
}

func (m macroChinaConsumerGoodsRetailDo) Clauses(conds ...clause.Expression) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m macroChinaConsumerGoodsRetailDo) Returning(value interface{}, columns ...string) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m macroChinaConsumerGoodsRetailDo) Not(conds ...gen.Condition) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m macroChinaConsumerGoodsRetailDo) Or(conds ...gen.Condition) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m macroChinaConsumerGoodsRetailDo) Select(conds ...field.Expr) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m macroChinaConsumerGoodsRetailDo) Where(conds ...gen.Condition) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m macroChinaConsumerGoodsRetailDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *macroChinaConsumerGoodsRetailDo {
	return m.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (m macroChinaConsumerGoodsRetailDo) Order(conds ...field.Expr) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m macroChinaConsumerGoodsRetailDo) Distinct(cols ...field.Expr) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m macroChinaConsumerGoodsRetailDo) Omit(cols ...field.Expr) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m macroChinaConsumerGoodsRetailDo) Join(table schema.Tabler, on ...field.Expr) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m macroChinaConsumerGoodsRetailDo) LeftJoin(table schema.Tabler, on ...field.Expr) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m macroChinaConsumerGoodsRetailDo) RightJoin(table schema.Tabler, on ...field.Expr) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m macroChinaConsumerGoodsRetailDo) Group(cols ...field.Expr) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m macroChinaConsumerGoodsRetailDo) Having(conds ...gen.Condition) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m macroChinaConsumerGoodsRetailDo) Limit(limit int) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m macroChinaConsumerGoodsRetailDo) Offset(offset int) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m macroChinaConsumerGoodsRetailDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m macroChinaConsumerGoodsRetailDo) Unscoped() *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Unscoped())
}

func (m macroChinaConsumerGoodsRetailDo) Create(values ...*model.MacroChinaConsumerGoodsRetail) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m macroChinaConsumerGoodsRetailDo) CreateInBatches(values []*model.MacroChinaConsumerGoodsRetail, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m macroChinaConsumerGoodsRetailDo) Save(values ...*model.MacroChinaConsumerGoodsRetail) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m macroChinaConsumerGoodsRetailDo) First() (*model.MacroChinaConsumerGoodsRetail, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MacroChinaConsumerGoodsRetail), nil
	}
}

func (m macroChinaConsumerGoodsRetailDo) Take() (*model.MacroChinaConsumerGoodsRetail, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MacroChinaConsumerGoodsRetail), nil
	}
}

func (m macroChinaConsumerGoodsRetailDo) Last() (*model.MacroChinaConsumerGoodsRetail, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MacroChinaConsumerGoodsRetail), nil
	}
}

func (m macroChinaConsumerGoodsRetailDo) Find() ([]*model.MacroChinaConsumerGoodsRetail, error) {
	result, err := m.DO.Find()
	return result.([]*model.MacroChinaConsumerGoodsRetail), err
}

func (m macroChinaConsumerGoodsRetailDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MacroChinaConsumerGoodsRetail, err error) {
	buf := make([]*model.MacroChinaConsumerGoodsRetail, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m macroChinaConsumerGoodsRetailDo) FindInBatches(result *[]*model.MacroChinaConsumerGoodsRetail, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m macroChinaConsumerGoodsRetailDo) Attrs(attrs ...field.AssignExpr) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m macroChinaConsumerGoodsRetailDo) Assign(attrs ...field.AssignExpr) *macroChinaConsumerGoodsRetailDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m macroChinaConsumerGoodsRetailDo) Joins(fields ...field.RelationField) *macroChinaConsumerGoodsRetailDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m macroChinaConsumerGoodsRetailDo) Preload(fields ...field.RelationField) *macroChinaConsumerGoodsRetailDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m macroChinaConsumerGoodsRetailDo) FirstOrInit() (*model.MacroChinaConsumerGoodsRetail, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MacroChinaConsumerGoodsRetail), nil
	}
}

func (m macroChinaConsumerGoodsRetailDo) FirstOrCreate() (*model.MacroChinaConsumerGoodsRetail, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MacroChinaConsumerGoodsRetail), nil
	}
}

func (m macroChinaConsumerGoodsRetailDo) FindByPage(offset int, limit int) (result []*model.MacroChinaConsumerGoodsRetail, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m macroChinaConsumerGoodsRetailDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m macroChinaConsumerGoodsRetailDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m macroChinaConsumerGoodsRetailDo) Delete(models ...*model.MacroChinaConsumerGoodsRetail) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *macroChinaConsumerGoodsRetailDo) withDO(do gen.Dao) *macroChinaConsumerGoodsRetailDo {
	m.DO = *do.(*gen.DO)
	return m
}
