// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/chenhaonan-eth/dao/dal/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSH300PE(db *gorm.DB, opts ...gen.DOOption) sH300PE {
	_sH300PE := sH300PE{}

	_sH300PE.sH300PEDo.UseDB(db, opts...)
	_sH300PE.sH300PEDo.UseModel(&model.SH300PE{})

	tableName := _sH300PE.sH300PEDo.TableName()
	_sH300PE.ALL = field.NewAsterisk(tableName)
	_sH300PE.Time = field.NewString(tableName, "time")
	_sH300PE.Date = field.NewFloat64(tableName, "date")
	_sH300PE.MiddleLyrPe = field.NewFloat64(tableName, "middle_lyr_pe")
	_sH300PE.LyrPe = field.NewFloat64(tableName, "lyr_pe")
	_sH300PE.AddLyrPe = field.NewFloat64(tableName, "add_lyr_pe")
	_sH300PE.MiddleTtmPe = field.NewFloat64(tableName, "middle_ttm_pe")
	_sH300PE.TtmPe = field.NewFloat64(tableName, "ttm_pe")
	_sH300PE.AddTtmPe = field.NewFloat64(tableName, "add_ttm_pe")

	_sH300PE.fillFieldMap()

	return _sH300PE
}

type sH300PE struct {
	sH300PEDo sH300PEDo

	ALL         field.Asterisk
	Time        field.String
	Date        field.Float64
	MiddleLyrPe field.Float64
	LyrPe       field.Float64
	AddLyrPe    field.Float64
	MiddleTtmPe field.Float64
	TtmPe       field.Float64
	AddTtmPe    field.Float64

	fieldMap map[string]field.Expr
}

func (s sH300PE) Table(newTableName string) *sH300PE {
	s.sH300PEDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sH300PE) As(alias string) *sH300PE {
	s.sH300PEDo.DO = *(s.sH300PEDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sH300PE) updateTableName(table string) *sH300PE {
	s.ALL = field.NewAsterisk(table)
	s.Time = field.NewString(table, "time")
	s.Date = field.NewFloat64(table, "date")
	s.MiddleLyrPe = field.NewFloat64(table, "middle_lyr_pe")
	s.LyrPe = field.NewFloat64(table, "lyr_pe")
	s.AddLyrPe = field.NewFloat64(table, "add_lyr_pe")
	s.MiddleTtmPe = field.NewFloat64(table, "middle_ttm_pe")
	s.TtmPe = field.NewFloat64(table, "ttm_pe")
	s.AddTtmPe = field.NewFloat64(table, "add_ttm_pe")

	s.fillFieldMap()

	return s
}

func (s *sH300PE) WithContext(ctx context.Context) *sH300PEDo { return s.sH300PEDo.WithContext(ctx) }

func (s sH300PE) TableName() string { return s.sH300PEDo.TableName() }

func (s sH300PE) Alias() string { return s.sH300PEDo.Alias() }

func (s *sH300PE) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sH300PE) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["time"] = s.Time
	s.fieldMap["date"] = s.Date
	s.fieldMap["middle_lyr_pe"] = s.MiddleLyrPe
	s.fieldMap["lyr_pe"] = s.LyrPe
	s.fieldMap["add_lyr_pe"] = s.AddLyrPe
	s.fieldMap["middle_ttm_pe"] = s.MiddleTtmPe
	s.fieldMap["ttm_pe"] = s.TtmPe
	s.fieldMap["add_ttm_pe"] = s.AddTtmPe
}

func (s sH300PE) clone(db *gorm.DB) sH300PE {
	s.sH300PEDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sH300PE) replaceDB(db *gorm.DB) sH300PE {
	s.sH300PEDo.ReplaceDB(db)
	return s
}

type sH300PEDo struct{ gen.DO }

func (s sH300PEDo) Debug() *sH300PEDo {
	return s.withDO(s.DO.Debug())
}

func (s sH300PEDo) WithContext(ctx context.Context) *sH300PEDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sH300PEDo) ReadDB() *sH300PEDo {
	return s.Clauses(dbresolver.Read)
}

func (s sH300PEDo) WriteDB() *sH300PEDo {
	return s.Clauses(dbresolver.Write)
}

func (s sH300PEDo) Session(config *gorm.Session) *sH300PEDo {
	return s.withDO(s.DO.Session(config))
}

func (s sH300PEDo) Clauses(conds ...clause.Expression) *sH300PEDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sH300PEDo) Returning(value interface{}, columns ...string) *sH300PEDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sH300PEDo) Not(conds ...gen.Condition) *sH300PEDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sH300PEDo) Or(conds ...gen.Condition) *sH300PEDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sH300PEDo) Select(conds ...field.Expr) *sH300PEDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sH300PEDo) Where(conds ...gen.Condition) *sH300PEDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sH300PEDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *sH300PEDo {
	return s.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (s sH300PEDo) Order(conds ...field.Expr) *sH300PEDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sH300PEDo) Distinct(cols ...field.Expr) *sH300PEDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sH300PEDo) Omit(cols ...field.Expr) *sH300PEDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sH300PEDo) Join(table schema.Tabler, on ...field.Expr) *sH300PEDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sH300PEDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sH300PEDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sH300PEDo) RightJoin(table schema.Tabler, on ...field.Expr) *sH300PEDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sH300PEDo) Group(cols ...field.Expr) *sH300PEDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sH300PEDo) Having(conds ...gen.Condition) *sH300PEDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sH300PEDo) Limit(limit int) *sH300PEDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sH300PEDo) Offset(offset int) *sH300PEDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sH300PEDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sH300PEDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sH300PEDo) Unscoped() *sH300PEDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sH300PEDo) Create(values ...*model.SH300PE) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sH300PEDo) CreateInBatches(values []*model.SH300PE, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sH300PEDo) Save(values ...*model.SH300PE) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sH300PEDo) First() (*model.SH300PE, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SH300PE), nil
	}
}

func (s sH300PEDo) Take() (*model.SH300PE, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SH300PE), nil
	}
}

func (s sH300PEDo) Last() (*model.SH300PE, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SH300PE), nil
	}
}

func (s sH300PEDo) Find() ([]*model.SH300PE, error) {
	result, err := s.DO.Find()
	return result.([]*model.SH300PE), err
}

func (s sH300PEDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SH300PE, err error) {
	buf := make([]*model.SH300PE, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sH300PEDo) FindInBatches(result *[]*model.SH300PE, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sH300PEDo) Attrs(attrs ...field.AssignExpr) *sH300PEDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sH300PEDo) Assign(attrs ...field.AssignExpr) *sH300PEDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sH300PEDo) Joins(fields ...field.RelationField) *sH300PEDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sH300PEDo) Preload(fields ...field.RelationField) *sH300PEDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sH300PEDo) FirstOrInit() (*model.SH300PE, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SH300PE), nil
	}
}

func (s sH300PEDo) FirstOrCreate() (*model.SH300PE, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SH300PE), nil
	}
}

func (s sH300PEDo) FindByPage(offset int, limit int) (result []*model.SH300PE, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sH300PEDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sH300PEDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sH300PEDo) Delete(models ...*model.SH300PE) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sH300PEDo) withDO(do gen.Dao) *sH300PEDo {
	s.DO = *do.(*gen.DO)
	return s
}
